# Generated by Django 5.1.7 on 2025-04-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_taskassignment_taskworker"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskWorker",
            new_name="TaskAssignment",
        ),
    ]
