# Generated by Django 5.1.7 on 2025-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_useractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("PROFILE_UPDATE", "Profile Updated"),
                    ("TASK_COMPLETE", "Task Completed"),
                    ("TASK_REOPENED", "Task Reopened"),
                    ("TASK_ASSIGNED", "Task Assigned"),
                ],
                max_length=20,
            ),
        ),
    ]
