# Generated by Django 5.1.7 on 2025-04-22 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_created_task_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("BLOCKS", "Blocks"),
                            ("DEPENDS_ON", "Depends On"),
                            ("RELATED", "Related"),
                            ("DUPLICATE", "Duplicate"),
                            ("PART_OF", "Part Of"),
                        ],
                        default="RELATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="tasks.task",
                    ),
                ),
                (
                    "target_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Relationship",
                "verbose_name_plural": "Task Relationships",
                "unique_together": {("source_task", "target_task")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="related_tasks",
            field=models.ManyToManyField(
                blank=True,
                through="tasks.TaskRelationship",
                to="tasks.task",
                verbose_name="Related Tasks",
            ),
        ),
    ]
